FROM python:3.10

WORKDIR /app

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY .  /app

RUN apt-get clean \
    && apt-get -y update \
    && pip install --upgrade pip

RUN pip install --no-cache-dir -r /app/requirements.txt

RUN adduser dockuser

RUN chmod 777 /app/execute.sh
RUN chown dockuser:dockuser -R /app

USER dockuser
ENTRYPOINT /app/execute.sh